name: ml4qick-onnx-env
channels:
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python=3.7
  - pytorch-cpu
  - pip 
  - pip:
    - git+https://github.com/fastmachinelearning/hls4ml.git@1c2acbbbf57db40a0a71253aab399f57e9295e46
    # pip install git+https://github.com/fastmachinelearning/hls4ml.git@8a17e2f6d650c6f51cba5356fa69cf372aa47e21  # <----- working ----->
    - numpy==1.20.3
    - matplotlib
    - tqdm 
    - h5py
    - notebook
    - torchvision==0.13.1
    - torchinfo 
    - pytorchcv
    - brevitas
    - pydot 
    - graphviz
